export const allTemplateMessagings = {
  status_code: 200,
  data: {
    items: [
      {
        id: "1",
        nama_template: "Welcome Email Template",
        perusahaan: "PT Aneka Tambang Tbk",
        category: "Communication & Announcements",
        trigger: "Registration Completed",
        body: "<h2>Welcome to Our Company!</h2><p>Dear <strong>[Name]</strong>,</p><p>We are excited to welcome you to our organization. This message contains important information to get you started.</p><ul><li>Check your employee handbook</li><li>Complete your onboarding tasks</li><li>Meet your team members</li></ul><p>Best regards,<br/>HR Team</p>",
        status: "Active",
        created_at: "2023-01-15T00:00:00.000Z",
        updated_at: "2023-01-15T00:00:00.000Z",
      },
      {
        id: "2",
        nama_template: "Project Update Notification",
        perusahaan: "PT Bukit Asam Tbk",
        category: "Notifications & Reminders",
        trigger: "Project Status",
        body: "<h2>Project Status Update</h2><p>Hello Team,</p><p>This is an automated update regarding project <strong>[Project Name]</strong>:</p><p><strong>Current Status:</strong> [Status]<br/><strong>Completion:</strong> [Percentage]%<br/><strong>Next Milestone:</strong> [Milestone]</p><p>Please review the attached documents and provide feedback by [Date].</p><p>Thank you,<br/>Project Management Office</p>",
        status: "Active",
        created_at: "2023-02-10T00:00:00.000Z",
        updated_at: "2023-02-10T00:00:00.000Z",
      },
      {
        id: "3",
        nama_template: "Meeting Reminder",
        perusahaan: "PT Freeport Indonesia",
        category: "Notifications & Reminders",
        trigger: "Meeting Scheduled (X hours before start)",
        body: "<h2>Meeting Reminder</h2><p>Dear [Name],</p><p>This is a friendly reminder about our upcoming meeting:</p><p><strong>Meeting:</strong> [Meeting Title]<br/><strong>Date:</strong> [Date]<br/><strong>Time:</strong> [Time]<br/><strong>Location:</strong> [Location]</p><p><strong>Agenda:</strong></p><ol><li>[Agenda Item 1]</li><li>[Agenda Item 2]</li><li>[Agenda Item 3]</li></ol><p>Please confirm your attendance.</p><p>Best regards,<br/>[Organizer Name]</p>",
        status: "Active",
        created_at: "2023-03-05T00:00:00.000Z",
        updated_at: "2023-03-05T00:00:00.000Z",
      },
      {
        id: "4",
        nama_template: "System Maintenance Notice",
        perusahaan: "PT Indonesia Asahan Aluminium (Inalum)",
        category: "System & Security Alerts",
        trigger: "Scheduled System Maintenance",
        body: "<h2>Scheduled System Maintenance</h2><p>Dear Users,</p><p>We would like to inform you about upcoming system maintenance:</p><p><strong>Maintenance Window:</strong> [Start Time] - [End Time]<br/><strong>Date:</strong> [Date]<br/><strong>Expected Duration:</strong> [Duration]</p><p><strong>Affected Systems:</strong></p><ul><li>[System 1]</li><li>[System 2]</li><li>[System 3]</li></ul><p>During this time, services may be temporarily unavailable. We apologize for any inconvenience.</p><p>IT Support Team</p>",
        status: "Inactive",
        created_at: "2023-04-12T00:00:00.000Z",
        updated_at: "2023-04-12T00:00:00.000Z",
      },
      {
        id: "5",
        nama_template: "Invoice Payment Reminder",
        perusahaan: "PT Timah Tbk",
        category: "Notifications & Reminders",
        trigger: "Due Date Approaching",
        body: "<h2>Payment Reminder</h2><p>Dear [Customer Name],</p><p>This is a friendly reminder that payment for invoice <strong>[Invoice Number]</strong> is due.</p><p><strong>Invoice Details:</strong></p><p><strong>Amount:</strong> [Amount]<br/><strong>Due Date:</strong> [Due Date]<br/><strong>Invoice Date:</strong> [Invoice Date]</p><p>Please ensure payment is made by the due date to avoid any late fees. If you have already made the payment, please disregard this message.</p><p>For questions, contact our billing department at [Contact Info].</p><p>Thank you,<br/>Billing Department</p>",
        status: "Active",
        created_at: "2023-05-18T00:00:00.000Z",
        updated_at: "2023-05-18T00:00:00.000Z",
      },
      {
        id: "6",
        nama_template: "Security Alert",
        perusahaan: "PT Vale Indonesia",
        category: "System & Security Alerts",
        trigger: "Login from New Device",
        body: "<h2>Security Alert</h2><p>Dear [User],</p><p><strong>IMPORTANT SECURITY NOTICE</strong></p><p>We detected unusual activity on your account:</p><p><strong>Event:</strong> [Event Type]<br/><strong>Time:</strong> [Timestamp]<br/><strong>Location:</strong> [Location]<br/><strong>IP Address:</strong> [IP Address]</p><p>If this was you, no action is required. If you don't recognize this activity:</p><ol><li>Change your password immediately</li><li>Review recent account activity</li><li>Contact our security team at [Contact]</li></ol><p>Stay safe,<br/>Security Team</p>",
        status: "Active",
        created_at: "2023-06-22T00:00:00.000Z",
        updated_at: "2023-06-22T00:00:00.000Z",
      },
      {
        id: "7",
        nama_template: "Holiday Announcement",
        perusahaan: "PT Aneka Tambang Tbk",
        category: "Communication & Announcements",
        trigger: "Event Created",
        body: "<h2>Holiday Announcement</h2><p>Dear Team,</p><p>We would like to announce the upcoming holiday schedule:</p><p><strong>Holiday:</strong> [Holiday Name]<br/><strong>Date:</strong> [Holiday Date]<br/><strong>Office Status:</strong> [Open/Closed]</p><p><strong>Special Instructions:</strong></p><ul><li>[Instruction 1]</li><li>[Instruction 2]</li><li>[Instruction 3]</li></ul><p>We wish everyone a wonderful holiday!</p><p>Best regards,<br/>Management</p>",
        status: "Inactive",
        created_at: "2023-07-08T00:00:00.000Z",
        updated_at: "2023-07-08T00:00:00.000Z",
      },
      {
        id: "8",
        nama_template: "Training Invitation",
        perusahaan: "PT Bukit Asam Tbk",
        category: "Communication & Announcements",
        trigger: "Event Created",
        body: "<h2>Training Program Invitation</h2><p>Dear [Employee Name],</p><p>You are invited to participate in our upcoming training program:</p><p><strong>Training:</strong> [Training Title]<br/><strong>Date:</strong> [Training Date]<br/><strong>Duration:</strong> [Duration]<br/><strong>Venue:</strong> [Location]<br/><strong>Instructor:</strong> [Instructor Name]</p><p><strong>Topics Covered:</strong></p><ul><li>[Topic 1]</li><li>[Topic 2]</li><li>[Topic 3]</li></ul><p>Please confirm your attendance by [RSVP Date].</p><p>Learning & Development Team</p>",
        status: "Active",
        created_at: "2023-08-14T00:00:00.000Z",
        updated_at: "2023-08-14T00:00:00.000Z",
      },
    ],
    meta: {
      total_page: 1,
      total: 8,
      page: 1,
      per_page: 10,
    },
  },
  version: "1.0.0",
};

export const templateMessagingDetail = (id) => {
  const template = allTemplateMessagings.data.items.find((item) => item.id === id);

  return {
    status_code: 200,
    data: template || null,
    version: "1.0.0",
  };
};
