export const getProjectChangeStatus = (projectId) => ({
  status_code: 200,
  data: {
    items: [
      {
        id: "1",
        project_id: projectId,
        date_changes: "2025-01-15T09:30:00.000Z",
        name: "Ahmad Hidayat",
        reason_for_change: "Initial project baseline setup and configuration completed. All initial parameters have been defined and approved by project stakeholders.",
      },
      {
        id: "2",
        project_id: projectId,
        date_changes: "2025-01-18T14:20:00.000Z",
        name: "Siti Nurhaliza",
        reason_for_change: "Budget adjustment required due to updated vendor pricing. CAPEX estimate increased by 5% to accommodate market fluctuations.",
      },
      {
        id: "3",
        project_id: projectId,
        date_changes: "2025-01-20T10:45:00.000Z",
        name: "Budi Santoso",
        reason_for_change: "Timeline extension approved. Additional 2 months added to project schedule to allow for comprehensive environmental assessment.",
      },
      {
        id: "4",
        project_id: projectId,
        date_changes: "2025-01-22T16:00:00.000Z",
        name: "Dewi Kartika",
        reason_for_change: "Scope change: Added renewable energy component to reduce carbon footprint. New sustainability requirements from board of directors.",
      },
      {
        id: "5",
        project_id: projectId,
        date_changes: "2025-01-25T11:15:00.000Z",
        name: "Eko Prasetyo",
        reason_for_change: "Technology vendor change from initial selection. New vendor offers better long-term support and more competitive pricing structure.",
      },
      {
        id: "6",
        project_id: projectId,
        date_changes: "2025-01-28T13:30:00.000Z",
        name: "Fitri Handayani",
        reason_for_change: "Risk mitigation strategy update. New safety protocols implemented based on recent industry standards and best practices.",
      },
      {
        id: "7",
        project_id: projectId,
        date_changes: "2025-02-01T08:00:00.000Z",
        name: "Gunawan Wijaya",
        reason_for_change: "Resource allocation adjustment. Additional engineering staff assigned to critical path activities to ensure on-time delivery.",
      },
      {
        id: "8",
        project_id: projectId,
        date_changes: "2025-02-05T15:45:00.000Z",
        name: "Hendra Kusuma",
        reason_for_change: "Quality standards enhancement. ISO certification requirements added to project deliverables as per management directive.",
      },
      {
        id: "9",
        project_id: projectId,
        date_changes: "2025-02-08T10:20:00.000Z",
        name: "Indah Permata",
        reason_for_change: "Stakeholder feedback incorporation. Design modifications requested by external consultants to improve operational efficiency.",
      },
      {
        id: "10",
        project_id: projectId,
        date_changes: "2025-02-12T14:00:00.000Z",
        name: "Joko Widodo",
        reason_for_change: "Regulatory compliance update. New environmental regulations require additional documentation and approval processes.",
      },
    ],
    meta: {
      total_page: 1,
      total: 10,
      page: 1,
      per_page: 10,
    },
  },
  version: "1.0.0",
});
